services:
  java-service:
    container_name: java-server
    image: java-server:prod
    build: .
    restart: always
    deploy:
      replicas: 1
    env_file:
      - ../envs/java_server.env
    networks:
      - db-net
    ports:
      - 8050:8050
networks:
  db-net: