version: "3.3"
services:
  atlantico-service:
    image: atlantico-server:v1
    container_name: atlantico-server
    restart: always
    deploy:
      replicas: 1
    environment:
      PORT: 8089
      CONTEXT: /mobile
      BD_ADDR: 192.168.0.15
      BD_ADDR: 192.168.0.15
      BD_PORT: 3306
      BD_NAME: emulator
      BD_USER: emulator
      BD_PASS: emulator
      LOG_LEVEL: info
    volumes:
      - $PWD/application.yml:/app/application.yml
    networks:
       - db-net
    ports:
      - 8089:8089

networks:
  db-net: