spring:
  application:    
    name: Emulador 
  profiles: "default"
  datasource:
    url: jdbc:mysql://192.168.0.15:3306/emulator?serverTimezone=America/Santiago&useSSL=false&allowPublicKeyRetrieval=true
    username: emulator
    password: emulator
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update # crea y borra las tablas sin persistencia (validate | update | create | create-drop )
      # validate: validate the schema, makes no changes to the database.
      # update: update the schema.
      # create: creates the schema, destroying previous data.
      # create-drop: drop the schema when the SessionFactory is closed explicitly, typically when the application is stopped.
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss" 
    
server:
  address: 0.0.0.0
  port: 8089
  
logging:
  level:
    org:
      hibernate:
        SQL: debug
    
http:
  timeout:
    connect: 90
    read: 90
    

